-- MySQL Script generated by MySQL Workbench
-- Sun 26 Jun 2016 03:57:31 BST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema communities
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `communities` ;

-- -----------------------------------------------------
-- Schema communities
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `communities` DEFAULT CHARACTER SET latin1 ;
USE `communities` ;

-- -----------------------------------------------------
-- Table `communities`.`resource_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `communities`.`resource_type` ;

CREATE TABLE IF NOT EXISTS `communities`.`resource_type` (
  `resource_type_id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `resource_type` VARCHAR(20) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`resource_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `communities`.`room_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `communities`.`room_type` ;

CREATE TABLE IF NOT EXISTS `communities`.`room_type` (
  `room_type_id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `room_type` VARCHAR(20) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`room_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `communities`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `communities`.`room` ;

CREATE TABLE IF NOT EXISTS `communities`.`room` (
  `room_id` SMALLINT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `room_name` VARCHAR(200) NULL DEFAULT NULL,
  `room_type_id` SMALLINT(5) unsigned NOT NULL,
  `room_desc` VARCHAR(200) NULL DEFAULT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`room_id`),
  INDEX `fk_room_room_type1_idx` (`room_type_id` ASC),
  CONSTRAINT `fk_room_room_type1`
    FOREIGN KEY (`room_type_id`)
    REFERENCES `communities`.`room_type` (`room_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;



-- -----------------------------------------------------
-- Table `communities`.`resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `communities`.`resource` ;

CREATE TABLE IF NOT EXISTS `communities`.`resource` (
  `resource_id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `address_id` SMALLINT(5) UNSIGNED NOT NULL,
  `resource_type_id` SMALLINT(5) UNSIGNED NOT NULL,
  `short_description` VARCHAR(200) NOT NULL,
  `page_file` VARCHAR(100) NULL DEFAULT NULL,
  `open_time` TIME NULL DEFAULT NULL,
  `close_time` TIME NULL DEFAULT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `room_id` SMALLINT(5) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`resource_id`),
  INDEX `fk_resource_resource_type1_idx` (`resource_type_id` ASC),
  INDEX `fk_resource_room1_idx` (`room_id` ASC),
  CONSTRAINT `fk_resource_resource_type1`
    FOREIGN KEY (`resource_type_id`)
    REFERENCES `communities`.`resource_type` (`resource_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resource_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `communities`.`room` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `communities`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `communities`.`address` ;

CREATE TABLE IF NOT EXISTS `communities`.`address` (
  `address_id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(50) NOT NULL,
  `address2` VARCHAR(50) NOT NULL,
  `address3` VARCHAR(20) NULL DEFAULT NULL,
  `town` SMALLINT(5) UNSIGNED NOT NULL,
  `postcode` VARCHAR(10) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `lat` FLOAT(10,6) NOT NULL,
  `lng` FLOAT(10,6) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_address_resource1_idx` (`address_id` ASC),
  CONSTRAINT `fk_address_resource1`
    FOREIGN KEY (`address_id`)
    REFERENCES `communities`.`resource` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `communities`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `communities`.`person` ;

CREATE TABLE IF NOT EXISTS `communities`.`person` (
  `person_id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(200) NULL DEFAULT NULL,
  `last_name` VARCHAR(200) NOT NULL,
  `title` VARCHAR(50) NULL DEFAULT NULL,
  `email_address` VARCHAR(255) NULL DEFAULT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `communities`.`person_link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `communities`.`person_link` ;

CREATE TABLE IF NOT EXISTS `communities`.`person_link` (
  `person_link_id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `person_id` SMALLINT(5) UNSIGNED NOT NULL,
  `address_id` SMALLINT(5) UNSIGNED NULL DEFAULT NULL,
  `resource_id` SMALLINT(5) UNSIGNED NULL DEFAULT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`person_link_id`),
  INDEX `person_id` (`person_id` ASC),
  INDEX `fk_person_link_address1_idx` (`address_id` ASC),
  CONSTRAINT `person_link_ibfk_1`
    FOREIGN KEY (`person_id`)
    REFERENCES `communities`.`person` (`person_id`),
  CONSTRAINT `fk_person_link_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `communities`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
